import { defineConfig } from 'oxlint';

export default defineConfig({
	options: {
		typeAware: true,
	},
	ignorePatterns: ['dist/**', '.agents/**', '.claude/**', '.codex/**', '.cursor/**'],
	categories: {
		correctness: 'error',
		suspicious: 'error',
		perf: 'off',
		style: 'off',
		restriction: 'off',
		pedantic: 'off',
		nursery: 'off',
	},
	plugins: ['typescript', 'unicorn', 'import', 'promise', 'oxc'],
	jsPlugins: ['./src/index.ts'],
	rules: {
		'no-console': 'error',
		complexity: ['error', { max: 20, variant: 'modified' }],
		'import/no-default-export': 'error',
		'import/no-cycle': 'error',
		'typescript/no-explicit-any': 'error',
		'typescript/no-non-null-assertion': 'error',
		'typescript/consistent-type-imports': 'error',
		'typescript/no-unused-vars': 'error',
		'typescript/no-floating-promises': 'error',
		'typescript/no-misused-promises': 'error',
		'typescript/await-thenable': 'error',
		'typescript/strict-boolean-expressions': 'error',
		'typescript/no-unnecessary-type-assertion': 'error',
		'typescript/no-unsafe-type-assertion': 'error',
		'typescript/no-unsafe-assignment': 'error',
		'typescript/no-unsafe-call': 'error',
		'typescript/no-unsafe-member-access': 'error',
		'typescript/no-unsafe-return': 'error',
		'typescript/no-unsafe-argument': 'error',
		'typescript/no-deprecated': 'error',
		'typescript/consistent-type-assertions': 'error',
		'unicorn/prefer-node-protocol': 'error',
		'unicorn/no-array-for-each': 'error',
		'unicorn/no-null': 'off',
		'promise/always-return': 'error',
		'promise/no-return-wrap': 'error',
		'anti-slop/no-chained-type-assertions': 'error',
		'anti-slop/no-conditional-empty-object-spread': 'error',
		'anti-slop/no-known-value-widening': 'error',
		'anti-slop/no-module-mocking': 'error',
		'anti-slop/no-object-parameters': 'error',
		'anti-slop/no-reflect-apply': 'error',
		'anti-slop/no-reflect-get': 'error',
		'anti-slop/no-runtime-typeof': ['error', { allowInTypeGuards: true }],
		'anti-slop/no-shape-in-symbol-names': 'error',
		'anti-slop/no-unknown-parameters': 'error',
		'anti-slop/no-unknown-returns': 'error',
		'anti-slop/no-unknown-type-aliases': 'error',
		'anti-slop/no-unsafe-dictionary-type': 'error',
		'anti-slop/no-widen-then-assert': 'error',
		'anti-slop/require-safety-comment-for-type-assertion': 'error',
	},
	overrides: [
		{
			files: ['**/*.test.ts', '**/*.spec.ts'],
			rules: {
				'no-console': ['error', { allow: ['info', 'warn', 'error'] }],
				'typescript/no-non-null-assertion': 'off',
				'typescript/no-unsafe-assignment': 'off',
				'typescript/no-unsafe-member-access': 'off',
				'typescript/no-unsafe-argument': 'off',
				'typescript/no-unsafe-return': 'off',
				'typescript/no-unsafe-call': 'off',
				'typescript/no-unsafe-type-assertion': 'off',
				'typescript/strict-boolean-expressions': 'off',
			},
		},
		{
			files: ['src/index.ts', 'src/effect/index.ts'],
			rules: {
				'import/no-default-export': 'off',
			},
		},
		{
			files: ['src/**/*.ts'],
			rules: {
				complexity: 'off',
				'no-underscore-dangle': 'off',
				'typescript/no-unnecessary-boolean-literal-compare': 'off',
				'typescript/no-unsafe-type-assertion': 'off',
				'anti-slop/no-unknown-parameters': 'off',
				'anti-slop/no-unknown-returns': 'off',
				'anti-slop/no-unsafe-dictionary-type': 'off',
				'anti-slop/no-chained-type-assertions': 'off',
				'anti-slop/require-safety-comment-for-type-assertion': 'off',
			},
		},
		{
			files: ['.changeset/**', '**/mise-tasks/**', '**/*.config.ts', '**/*.config.mjs'],
			rules: {
				'import/no-default-export': 'off',
				'no-console': ['error', { allow: ['info', 'warn', 'error'] }],
				'anti-slop/no-unknown-parameters': 'off',
				'anti-slop/no-unsafe-dictionary-type': 'off',
				'anti-slop/no-runtime-typeof': 'off',
			},
		},
	],
});
